### ISSUE TITLE
Incluir Ley de Infogobierno

### ISSUE THREAD

**Issue by risturiz** [cslve/reglamento-conati#1]
Dentro del reglamento se hacen referencias especificas a la Ley, creo conveniente si alguien la tiene disponible incluirla dentro del repo para consultarla a medida que se vaya desarrollando el mismo.

**Comment by nhomar** [comment]
me voy por el link a la fuente oficial externa, pero sí debe haber un link.

**Comment by 3rn3st0** [comment]
Ahí dejo el enlace directo al PDF: **[Ley de Infogobierno](http://www.conatel.gob.ve/files/leyinfog.pdf)**

**Comment by ghostbar** [comment]
Fue agregado en f57ea86376b1466168dee3d4e32819f55288cbf7
