### ISSUE TITLE
[DOC] 3rn3st0: Concepto de Administración Pública Nacional

### ISSUE THREAD

**Issue by 3rn3st0** [cslve/reglamento-conati#7]
Artículo XX. A todos los efectos de éste Reglamento, se entiende por Administración Pública Nacional:
1. Los órganos y entes que ejercen el Poder Público Nacional, Estadal, Municipal, en los distritos metropolitanos, en las dependencias federales y en las demás entidades locales previstas en la Ley Orgánica del Poder Público Municipal.
2. Los institutos públicos nacionales, estadales, de los distritos metropolitanos y municipales.
3. El Banco Central de Venezuela.
4. Las universidades públicas, así como cualquier otra institución del sector universitario de
   naturaleza pública.
5. Las demás personas de derecho público nacionales, estadales, distritales y municipales.
6. Las sociedades de cualquier naturaleza, las fundaciones, empresas, asociaciones civiles y las demás creadas con fondos públicos.
7. Las organizaciones y expresiones organizativas del Poder Popular.
8. Las personas naturales o jurídicas, en cuanto les sea aplicable, en los términos establecidos en este Reglamento.
9. Las demás que establezca la Ley.

Parágrafo único: A todos los efectos de éste reglamento, podrán usarse las siglas **APN** para hacer referencia a la Administración Pública Nacional.

**Comment by 3rn3st0** [comment]
Propuesta de definición del concepto de **Administración Pública Nacional**. Dentro del documento base, no vi un lugar donde pudiera ubicar éste concepto, por eso lo redacté como un **issue**.

**Comment by petrizzo** [comment]
Hola.
El texto indica lo que forma parte de la APN no lo que la APN es. Por otro lado, los numerales 7, 8 y 9 no se corresponden con componentes de la APN.

Pareciera que la propuesta tiene que ver con los sujetos de ley del reglamento, sin embargo, esos sujetos de ley deben ser heredados del articulado de la LEy.

**Comment by 3rn3st0** [comment]
Ciertamente @petrizzo, esos sujetos deberían ser heredados de la Ley, pero en la misma jamás se menciona al reglamento y, en estos casos, dejar algo a criterio o interpretación de quien lee la ley no me parece correcto. Prefiero pecar de redundante a dejar que alguien pueda luego decir: "Eso no está en la ley".

En alguna parte escribí sobre el hecho de que la Ley jamás menciona al reglamento.

En cuanto a los numerales, sí, tienes razón: Los numerales 7 y 8 podrían ser eliminados ya que el Poder Popular no es APN y tampoco las personas de derecho privado, sin embargo el último debe quedarse. Esa muletilla sirve para abarcar cualesquiera otros entes que pudieran escaparse a los mencionados en los primeros seis numerales.

**Comment by ghostbar** [comment]
El 7, 8 y 9 están definidos en la ley en el artículo 2 de la LIG, donde se define el ámbito de aplicación de la ley (y que termina siendo más amplio que esta definición).

El concepto de APN es sencillo: Toda persona de derecho público nacional, estatal, distrital o municipal que ejerza el Poder Público de forma alguna.

**Comment by ghostbar** [comment]
También puede ser: «Toda persona de derecho público que realice la función administrativa y de gestión del Estado.»

**Comment by petrizzo** [comment]
Hola. Veamos un ejemplo porque creo que se habla de dos cosas que tienen que ver pero estan en dos niveles diferentes.

1) Definición de Administración Pública Nacional: No nos sirve "toda persona de derecho público que realice la funcón administrativa y de gestión del Estado" porque esto incluye a organos que cumplen estas tareas desde otras áreas distintas a la Administración Pública Nacional. Por ejemplo el Ministerio Público, es sujeto de derecho público pero no hace gestiones de administración de Estado y si de gestiones de defensa de los derechos de los ciudadanos o de patrimonio del Estado que es UNA parte. Tanto la CRBV como la LOAPN hacen referencia a tareas de gestión de actividades de Estado, pero hay que entender que no todas las personas sujeto de derecho público hacen esto. Nuevamente, acudir a una definición de wikipedia y tunearla es insuficiente. De hecho, nuestra CRBV parece circunscribir el concepto de APN de modo -casi- exclusivo al Ejecutivo Nacional. Sin embargo, mi punto, en el fondo es: a) no es necesario definir ¿qué es APN? sino abordar cuáles son los sujetos objeto del reglamento y estos no pueden ser otros que los que señale la Ley de infogobierno. Y eso ya está escrito. No hay que inventar la rueda. Just KISS

2) Sobre el comentario de @3rn3st0 de que "En alguna parte escribí sobre el hecho de que la Ley jamás menciona al reglamento." realmente no se de qué ley habla. Si es la de infogobierno lo menciona 9 veces, 4 de las cuales tienen que ver con el reglamento de la ley y no con reglamentos internos de los entes que ésta diseña.

**Comment by petrizzo** [comment]
No se si @3rn3st0 sabe del uso de la palabra "muletilla" en todo cso "los demás que establezca esta ley" no es una muletila.

**Comment by petrizzo** [comment]
Con respecto a los numerales 7, 8 y 9 ... por los clavos de cristo, no se compliquen. déjenlos y ya. Tan sólo no digan que esos numerales son la definición de la APN porque NO-LO-SON

**Comment by ghostbar** [comment]
¿No podías decir "no tenemos que definir que es la APN, está en X lugar" desde el principio?

**Comment by 3rn3st0** [comment]
Bueno, listo, entendido el punto: NO se define APN dentro del reglamento porque no hace falta.

Por mi, pueden cerrar el issue. No tiene sentido que siga abierto.
